version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      ALLOW_PLAINTEXT_LISTENER: "yes"

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    image: fraud-demo-producer
    depends_on:
      - kafka
    volumes:
      - ./data:/data  # tylko dane, kod jest już w obrazie
    restart: unless-stopped

  trainer:
    build:
      context: .
      dockerfile: model/Dockerfile
    image: fraud-demo-trainer
    depends_on:
      - kafka
    volumes:
      - ./model:/model
      - ./data:/data
    restart: "no"

  consumer:
    build:
      context: .
      dockerfile: consumer_spark/Dockerfile
    image: fraud-demo-consumer
    depends_on:
      - kafka
      - websocket
    volumes:
      - ./model:/model
    restart: unless-stopped

  websocket:
    build: ./websocket
    image: fraud-websocket
    ports:
      - "5000:5000"
    volumes:
      - ./websocket:/app
    restart: unless-stopped
